### PR TITLE
Add a few CMSIS-Pack updates

### LINKED ISSUE #203: Support style attribute on flash algorithms
There seems to be a *style* attribute on the flash algorithm description in the .pdsc file, which I encountered the first time today. It's described in the [spec](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#element_algorithm).

It would be nice to have this available in the Rust crate, currently it doesn't seem to be there.

### PR DESCRIPTION
**Pull request by mbrossard**
Intended to fix #203 (@Tiwalun: can you confirm?)
Adds other cores not added by #204

### CODE REVIEW

**Comment by Tiwalun** [comment]
Looks good, thanks for adding this!

Do you know if the "CMSIS" style of flash algorithms is described anywhere?

**Comment by mbrossard** [comment]
> Looks good, thanks for adding this!

You are welcome. I did this one quickly and I will soon push out a patch release, but I think I need to go over all the updates, and that might warrant a larger bump in version.

> Do you know if the "CMSIS" style of flash algorithms is described anywhere?

My read from the [specifications](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#AlgorithmStyleEnum) is that it might now be finalized yet.

**Comment by flit** [comment]
> My read from the [specifications](https://open-cmsis-pack.github.io/Open-CMSIS-Pack-Spec/main/html/pdsc_family_pg.html#AlgorithmStyleEnum) is that it might now be finalized yet.

I guess you meant "might not be finalized yet", because it isn't. There is no specification of a "CMSIS" flash algo style being considered, afaik.

**Comment by mbrossard** [comment]
> I guess you meant "might not be finalized yet", because it isn't. 
That's what I meant

**Pull request merged**
